language: node_js
node_js:
  - "node" # Latest stable

deploy:
  provider: pages
  skip-cleanup: true
  target-branch: master
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: dist
  on:
    branch: develop

branches:
  except:
    master

script:
  - npm run lint
  - npm run build
